import type { Metadata } from "next";
import { SimplePageLayout } from "@/components/content/simple-page-layout";
import { JsonLd } from "@/components/seo/json-ld";
import { createPageMetadata } from "@/lib/seo/metadata";
import { breadcrumbSchema, webPageSchema } from "@/lib/seo/schema";
import { supportPages } from "@/lib/site";

const page = supportPages.terms;

export const metadata: Metadata = createPageMetadata({
  title: page.title,
  description: page.description,
  path: page.path,
  keywords: page.keywords,
});

export default function TermsPage() {
  return (
    <>
      <JsonLd
        data={[
          webPageSchema({
            title: page.title,
            description: page.description,
            path: page.path,
            keywords: page.keywords,
          }),
          breadcrumbSchema([
            { name: "Home", path: "/" },
            { name: page.breadcrumbName, path: page.path },
          ]),
        ]}
      />
      <SimplePageLayout
        eyebrow="Terms and disclaimer"
        title="Informational tool, not a hiring guarantee"
        intro="ApplyReadyCV provides practical resume feedback for editing and self-review. It is not a recruiting service, legal adviser, employment adviser, or guarantee of any application outcome."
        sections={[
          {
            title: "Informational only",
            body: "The checker provides general feedback on common resume readability, keyword, completeness, and application-fit issues. It should not be treated as professional, legal, or employment advice.",
          },
          {
            title: "No job, interview, or ATS guarantee",
            body: "ApplyReadyCV cannot guarantee interviews, job offers, recruiter decisions, ATS approval, or employer responses. Hiring decisions depend on many factors outside this tool.",
          },
          {
            title: "Scoring is approximate",
            body: "Scores are generated by deterministic rules and simple keyword matching. They are meant to guide editing decisions, not certify that a resume is complete, accurate, or acceptable to any employer.",
          },
          {
            title: "User responsibility",
            body: "You are responsible for reviewing recommendations, ensuring your resume is truthful, and making final application decisions. Do not add keywords, credentials, or experience you cannot support.",
          },
          {
            title: "Current availability",
            body: "This MVP is provided for Vercel Hobby development and testing. It may change, break, or be expanded over time.",
          },
        ]}
        cta={{ label: "Use the checker", href: "/#checker" }}
      />
    </>
  );
}
