import type { AnalysisMode } from "./types";

export type RoleFamily = {
  id: string;
  name: string;
  titles: string[];
  keywords: string[];
  senioritySignals: string[];
  proofSignals: string[];
  modeFit: AnalysisMode[];
};

export const roleFamilies: RoleFamily[] = [
  {
    id: "it-support-helpdesk",
    name: "IT Support / Helpdesk",
    titles: [
      "IT Support Specialist",
      "Helpdesk Analyst",
      "Desktop Support Technician",
      "Junior Systems Administrator",
      "Service Desk Analyst",
    ],
    keywords: [
      "it support",
      "helpdesk",
      "help desk",
      "service desk",
      "troubleshooting",
      "ticketing",
      "tickets",
      "desktop support",
      "hardware",
      "software support",
      "active directory",
      "windows",
      "network support",
      "vpn",
      "endpoint",
      "microsoft 365",
    ],
    senioritySignals: [
      "systems administration",
      "escalation",
      "root cause",
      "incident management",
      "service improvement",
    ],
    proofSignals: [
      "ticket resolution",
      "hardware troubleshooting",
      "software troubleshooting",
      "active directory",
      "network troubleshooting",
      "endpoint support",
      "user support",
    ],
    modeFit: ["remote", "local"],
  },
  {
    id: "technical-support",
    name: "Technical Support",
    titles: [
      "Technical Support Associate",
      "Product Support Specialist",
      "Customer Technical Support",
      "Support Engineer",
      "Technical Support Representative",
    ],
    keywords: [
      "technical support",
      "product support",
      "troubleshooting",
      "customer issues",
      "bug report",
      "escalation",
      "support tickets",
      "zendesk",
      "freshdesk",
      "intercom",
      "knowledge base",
      "saas",
      "diagnostics",
      "customer success",
    ],
    senioritySignals: [
      "tier 2",
      "tier 3",
      "escalation ownership",
      "support process",
      "knowledge base ownership",
    ],
    proofSignals: [
      "ticket handling",
      "customer troubleshooting",
      "product knowledge",
      "bug triage",
      "technical documentation",
      "support tools",
    ],
    modeFit: ["remote", "local"],
  },
  {
    id: "software-development",
    name: "Software Development",
    titles: [
      "Software Developer",
      "Junior Software Engineer",
      "Application Developer",
      "Backend Developer",
      "Full Stack Developer",
    ],
    keywords: [
      "software developer",
      "software engineer",
      "programming",
      "application development",
      "backend",
      "api",
      "database",
      "javascript",
      "typescript",
      "python",
      "java",
      "c#",
      "node.js",
      "git",
      "github",
      "unit tests",
    ],
    senioritySignals: [
      "architecture",
      "code review",
      "technical design",
      "lead developer",
      "mentored engineers",
    ],
    proofSignals: [
      "shipped features",
      "code repository",
      "api development",
      "database design",
      "testing",
      "debugging",
      "version control",
    ],
    modeFit: ["remote", "freelance", "local"],
  },
  {
    id: "web-development",
    name: "Web Development",
    titles: [
      "Web Developer",
      "Frontend Developer",
      "WordPress Developer",
      "React Developer",
      "Website Specialist",
    ],
    keywords: [
      "web development",
      "frontend",
      "front end",
      "website",
      "html",
      "css",
      "javascript",
      "react",
      "next.js",
      "wordpress",
      "shopify",
      "responsive design",
      "cms",
      "landing page",
      "seo",
    ],
    senioritySignals: [
      "technical lead",
      "design system",
      "performance optimization",
      "web architecture",
      "conversion strategy",
    ],
    proofSignals: [
      "live website",
      "portfolio",
      "responsive layout",
      "cms work",
      "site performance",
      "accessibility",
      "front-end implementation",
    ],
    modeFit: ["remote", "freelance", "local"],
  },
  {
    id: "qa-software-testing",
    name: "QA / Software Testing",
    titles: [
      "QA Tester",
      "Software Test Analyst",
      "QA Support Assistant",
      "Manual QA Tester",
      "Junior QA Analyst",
    ],
    keywords: [
      "qa",
      "quality assurance",
      "software testing",
      "test cases",
      "test plans",
      "manual testing",
      "automated tests",
      "regression testing",
      "bug tracking",
      "jira",
      "defect",
      "uat",
      "selenium",
      "playwright",
      "acceptance testing",
    ],
    senioritySignals: [
      "test strategy",
      "qa lead",
      "automation framework",
      "release quality",
      "test coverage",
    ],
    proofSignals: [
      "test cases",
      "bug reports",
      "regression testing",
      "qa tools",
      "release testing",
      "defect tracking",
    ],
    modeFit: ["remote", "freelance", "local"],
  },
  {
    id: "data-entry-admin-support",
    name: "Data Entry / Admin Support",
    titles: [
      "Data Entry Specialist",
      "Administrative Assistant",
      "Admin Support Specialist",
      "Office Assistant",
      "Records Clerk",
    ],
    keywords: [
      "data entry",
      "admin",
      "administrative",
      "records",
      "filing",
      "data accuracy",
      "spreadsheets",
      "excel",
      "google sheets",
      "document processing",
      "scheduling",
      "clerical",
      "back office",
      "database entry",
    ],
    senioritySignals: [
      "office coordination",
      "process improvement",
      "records management",
      "administrative lead",
      "reporting ownership",
    ],
    proofSignals: [
      "accurate data entry",
      "records management",
      "spreadsheet work",
      "document control",
      "scheduling",
      "administrative coordination",
    ],
    modeFit: ["remote", "freelance", "local"],
  },
  {
    id: "virtual-assistant",
    name: "Virtual Assistant",
    titles: [
      "Virtual Assistant",
      "Executive Virtual Assistant",
      "Remote Admin Assistant",
      "Online Business Assistant",
      "Freelance VA",
    ],
    keywords: [
      "virtual assistant",
      "va",
      "calendar management",
      "email management",
      "travel booking",
      "research",
      "client communication",
      "online tools",
      "google workspace",
      "microsoft office",
      "crm",
      "inbox management",
      "appointment setting",
      "administrative support",
    ],
    senioritySignals: [
      "executive support",
      "operations support",
      "client onboarding",
      "workflow improvement",
      "team coordination",
    ],
    proofSignals: [
      "calendar management",
      "email management",
      "client communication",
      "admin systems",
      "research tasks",
      "remote collaboration",
    ],
    modeFit: ["remote", "freelance"],
  },
  {
    id: "customer-support",
    name: "Customer Support",
    titles: [
      "Customer Support Representative",
      "Customer Service Associate",
      "Call Center Agent",
      "Client Support Specialist",
      "Customer Experience Associate",
    ],
    keywords: [
      "customer support",
      "customer service",
      "call center",
      "bpo",
      "inbound calls",
      "outbound calls",
      "chat support",
      "email support",
      "customer inquiries",
      "complaints",
      "crm",
      "zendesk",
      "salesforce",
      "client support",
      "customer satisfaction",
    ],
    senioritySignals: [
      "team lead",
      "quality monitoring",
      "support metrics",
      "escalation handling",
      "coaching agents",
    ],
    proofSignals: [
      "customer inquiries",
      "ticket handling",
      "call handling",
      "chat support",
      "crm tools",
      "customer satisfaction",
    ],
    modeFit: ["remote", "local"],
  },
  {
    id: "sales-business-development",
    name: "Sales / Business Development",
    titles: [
      "Sales Associate",
      "Business Development Representative",
      "Account Executive",
      "Sales Development Representative",
      "Lead Generation Specialist",
    ],
    keywords: [
      "sales",
      "business development",
      "lead generation",
      "prospecting",
      "pipeline",
      "crm",
      "cold calling",
      "outreach",
      "negotiation",
      "quota",
      "revenue",
      "account management",
      "hubspot",
      "salesforce",
      "closing",
    ],
    senioritySignals: [
      "sales strategy",
      "team target",
      "forecasting",
      "account planning",
      "territory management",
    ],
    proofSignals: [
      "sales targets",
      "lead generation",
      "crm pipeline",
      "client outreach",
      "revenue results",
      "account management",
    ],
    modeFit: ["remote", "freelance", "local"],
  },
  {
    id: "marketing-content",
    name: "Marketing / Content",
    titles: [
      "Marketing Assistant",
      "Content Writer",
      "Social Media Specialist",
      "Digital Marketing Associate",
      "Content Marketing Specialist",
    ],
    keywords: [
      "marketing",
      "content",
      "copywriting",
      "social media",
      "email marketing",
      "seo",
      "campaigns",
      "analytics",
      "brand",
      "blog",
      "newsletter",
      "canva",
      "meta ads",
      "google analytics",
      "content calendar",
    ],
    senioritySignals: [
      "marketing strategy",
      "campaign ownership",
      "brand strategy",
      "content strategy",
      "budget management",
    ],
    proofSignals: [
      "campaign results",
      "content samples",
      "social media metrics",
      "email performance",
      "seo work",
      "marketing tools",
    ],
    modeFit: ["remote", "freelance", "local"],
  },
  {
    id: "graphic-design-creative",
    name: "Graphic Design / Creative",
    titles: [
      "Graphic Designer",
      "Visual Designer",
      "Creative Assistant",
      "Brand Designer",
      "Multimedia Designer",
    ],
    keywords: [
      "graphic design",
      "visual design",
      "branding",
      "creative",
      "adobe photoshop",
      "illustrator",
      "figma",
      "canva",
      "layout",
      "typography",
      "logo",
      "social graphics",
      "marketing materials",
      "portfolio",
      "multimedia",
    ],
    senioritySignals: [
      "creative direction",
      "brand system",
      "art direction",
      "design lead",
      "visual strategy",
    ],
    proofSignals: [
      "design portfolio",
      "brand assets",
      "layout work",
      "creative tools",
      "marketing graphics",
      "visual samples",
    ],
    modeFit: ["remote", "freelance", "local"],
  },
  {
    id: "hr-recruitment",
    name: "HR / Recruitment",
    titles: [
      "HR Assistant",
      "Recruitment Coordinator",
      "Talent Acquisition Associate",
      "HR Generalist",
      "HR Manager",
    ],
    keywords: [
      "hr",
      "human resources",
      "recruitment",
      "talent acquisition",
      "interview scheduling",
      "employee relations",
      "onboarding",
      "payroll",
      "benefits",
      "hris",
      "labor compliance",
      "people management",
      "performance management",
      "policy",
      "employee records",
    ],
    senioritySignals: [
      "hr manager",
      "people management",
      "employee relations",
      "labor compliance",
      "policy ownership",
      "workforce planning",
    ],
    proofSignals: [
      "HR operations",
      "recruitment",
      "employee relations",
      "labor compliance",
      "people management",
      "payroll or benefits administration",
      "HRIS tools",
    ],
    modeFit: ["remote", "local"],
  },
  {
    id: "accounting-bookkeeping",
    name: "Accounting / Bookkeeping",
    titles: [
      "Bookkeeper",
      "Accounting Assistant",
      "Accounts Payable Clerk",
      "Accounts Receivable Clerk",
      "Finance Assistant",
    ],
    keywords: [
      "accounting",
      "bookkeeping",
      "accounts payable",
      "accounts receivable",
      "invoice",
      "reconciliation",
      "quickbooks",
      "xero",
      "financial records",
      "payroll",
      "expense reports",
      "billing",
      "tax",
      "ledger",
      "cash flow",
    ],
    senioritySignals: [
      "financial reporting",
      "month end",
      "audit support",
      "accounting controls",
      "budget tracking",
    ],
    proofSignals: [
      "invoice processing",
      "reconciliation",
      "bookkeeping tools",
      "financial records",
      "payroll support",
      "billing accuracy",
    ],
    modeFit: ["remote", "freelance", "local"],
  },
  {
    id: "project-management",
    name: "Project Management",
    titles: [
      "Project Coordinator",
      "Project Manager",
      "Program Assistant",
      "Delivery Coordinator",
      "Scrum Coordinator",
    ],
    keywords: [
      "project management",
      "project coordinator",
      "timeline",
      "deliverables",
      "stakeholders",
      "scope",
      "risk",
      "budget",
      "jira",
      "asana",
      "trello",
      "scrum",
      "agile",
      "status reporting",
      "milestones",
    ],
    senioritySignals: [
      "project manager",
      "program management",
      "budget ownership",
      "team leadership",
      "stakeholder management",
    ],
    proofSignals: [
      "project timelines",
      "stakeholder updates",
      "deliverable tracking",
      "risk tracking",
      "project tools",
      "cross-functional coordination",
    ],
    modeFit: ["remote", "freelance", "local"],
  },
  {
    id: "operations",
    name: "Operations",
    titles: [
      "Operations Assistant",
      "Operations Coordinator",
      "Business Operations Associate",
      "Process Coordinator",
      "Office Operations Specialist",
    ],
    keywords: [
      "operations",
      "process",
      "workflow",
      "sop",
      "standard operating procedure",
      "coordination",
      "vendor",
      "inventory",
      "reporting",
      "logistics",
      "scheduling",
      "process improvement",
      "documentation",
      "business operations",
      "office operations",
    ],
    senioritySignals: [
      "operations manager",
      "process ownership",
      "team coordination",
      "budget ownership",
      "operational strategy",
    ],
    proofSignals: [
      "process documentation",
      "workflow improvement",
      "vendor coordination",
      "operations reporting",
      "inventory tracking",
      "scheduling coordination",
    ],
    modeFit: ["remote", "local"],
  },
  {
    id: "healthcare-support",
    name: "Healthcare Support",
    titles: [
      "Healthcare Support Assistant",
      "Medical Receptionist",
      "Patient Support Representative",
      "Clinic Administrative Assistant",
      "Medical Records Clerk",
    ],
    keywords: [
      "healthcare",
      "medical",
      "clinic",
      "patient",
      "patient support",
      "medical records",
      "appointment scheduling",
      "insurance",
      "billing",
      "hipaa",
      "front desk",
      "care coordination",
      "emr",
      "ehr",
      "claims",
    ],
    senioritySignals: [
      "clinic coordination",
      "patient care coordination",
      "compliance",
      "medical office lead",
      "healthcare operations",
    ],
    proofSignals: [
      "patient scheduling",
      "medical records",
      "healthcare systems",
      "insurance support",
      "front desk support",
      "patient communication",
    ],
    modeFit: ["local", "remote"],
  },
  {
    id: "education-training",
    name: "Education / Training",
    titles: [
      "Training Assistant",
      "Tutor",
      "Instructional Support Specialist",
      "Learning Coordinator",
      "Education Assistant",
    ],
    keywords: [
      "education",
      "training",
      "teaching",
      "tutor",
      "curriculum",
      "lesson plans",
      "instruction",
      "learning",
      "coaching",
      "workshops",
      "lms",
      "student support",
      "assessment",
      "facilitation",
      "onboarding training",
    ],
    senioritySignals: [
      "training manager",
      "curriculum design",
      "learning strategy",
      "program lead",
      "instructional design",
    ],
    proofSignals: [
      "training delivery",
      "lesson planning",
      "student support",
      "learning materials",
      "assessment",
      "workshop facilitation",
    ],
    modeFit: ["remote", "freelance", "local"],
  },
];
